function run_permucorr_examples
%RUN_PERMUCORR_EXAMPLES  Run permutation correlation examples.
%   Generates random multivariate data for 2 "dependent" samples X and Y.
%   Each sample has 20 variables, each pair with a correlation of 0, except
%   for the first 5 variables which have a weak positive correlation, and
%   the next 5 variables which have a strong negative correlation. Each
%   variable has 30 observations. Permutation-based correlation measures
%   based on the Pearson and Spearman's rank correlation coefficients are
%   performed between the corresponding variables of each sample for
%   two-tailed, right-tailed and left-tailed tests. The results are
%   compared to those of the equivalent parametric correlation measure
%   (Pearson's correlation coefficient), and non-parametric correlation
%   measure (Spearman's rank correlation coefficient) using MATLAB's corr.m
%   and corrcoef.m.
%
%   Note: For right-tailed and left-tailed correlation measures, the
%   confidence intervals (CIs) generated by MATLAB's corrcoef.m are based
%   on two-tailed correlation measures with the alpha level set to alpha*2,
%   as there is no option to specify the test tail in corrcoef.m.
%
%   See also PERMUCORR CORR CORRCOEF.
%
%   PERMUTOOLS https://github.com/mickcrosse/PERMUTOOLS

%   References:
%       [1] Crosse MJ, Foxe JJ, Molholm S (2024) PERMUTOOLS: A MATLAB
%           Package for Multivariate Permutation Testing. arXiv 2401.09401.

%   © 2018-2026 Mick Crosse <crossemj@tcd.ie>
%   CNL, Albert Einstein College of Medicine, NY.
%   TCBE, Trinity College Dublin, Ireland.

close all; clc;

% Set up experiment
insert_nan = false;
nobs = 30; nvar = 20;
xaxis = 1:nvar; alpha = 0.05;
tail = {'both','right','left'};
label = {'two','right','left'};
type = {'pearson','spearman'};
symbol = {'{\itr}','{\itρ}'};

% Generate random data
rng(42);
x = randn(nobs,nvar);
y = randn(nobs,nvar);
idx1 = round(nvar/4);
idx2 = round(nvar/2);
y(:,1:idx1) = y(:,1:idx1)+x(:,1:idx1)/2;
y(:,idx1:idx2) = y(:,idx1:idx2)-x(:,idx1:idx2);
if insert_nan
    x(1,1) = NaN;
end

for t = 1:numel(type)

    disp(type{t})

    toc1 = zeros(numel(tail)*2,1);
    toc2 = zeros(numel(tail)*2,1);
    toc3 = zeros(numel(tail)*2,1);

    f1 = figure('Name',[type{t},'''s correlation: coefficients & CIs'],...
        'NumberTitle','off');
    set(gcf,'color','w')
    f2 = figure('Name',[type{t},'''s correlation: p-values'],...
        'NumberTitle','off');
    set(gcf,'color','w')

    for i = 1:numel(tail)

        % Parametric test
        tic
        [r1,p1] = corr(x,y,'tail',tail{i},'type',type{t});
        r1 = diag(r1); p1 = diag(p1);
        ci1 = zeros(2,nvar);
        switch tail{i}
            case 'both'
                cialpha = alpha;
            case {'right','left'}
                cialpha = alpha*2;
        end
        for j = 1:nvar
            switch type{t}
                case 'pearson'
                    [~,~,clwr,cupr] = corrcoef(x(:,j),y(:,j),...
                        'Alpha',cialpha);
                case 'spearman'
                    [~,~,clwr,cupr] = corrcoef(tiedrank(x(:,j)),...
                        tiedrank(y(:,j)),'Alpha',cialpha);
            end
            switch tail{i}
                case 'both'
                    ci1(:,j) = [clwr(2);cupr(2)];
                case 'right'
                    ci1(:,j) = [clwr(2);Inf];
                case 'left'
                    ci1(:,j) = [-Inf;cupr(2)];
            end
        end
        toc1(i) = toc;

        % Permutation test (uncorrected)
        tic
        [r2,p2,ci2] = permucorr(x,y,'tail',tail{i},'type',type{t},...
            'correct',0);
        toc2(i) = toc;

        % Permutation test (max-corrected)
        tic
        [r3,p3,ci3] = permucorr(x,y,'tail',tail{i},'type',type{t},...
            'correct',1);
        toc3(i) = toc;

        % Plot statistic & CIs
        figure(f1)
        subplot(3,2,i+i-1), hold on
        plot(xaxis,r1,xaxis,r2,'--','LineWidth',2)
        plot(xaxis,ci1,'k',xaxis,ci2,'--r')
        plot(xaxis(p1<=alpha),r1(p1<=alpha),'ok','LineWidth',2)
        plot(xaxis(p2<=alpha),r2(p2<=alpha),'xr','LineWidth',2)
        xlim([0,nvar+1]), ylim([-1,1]), box on, grid on
        if i == 1
            title('Uncorrected')
        elseif i == 3
            xlabel('variable')
        end
        ylabel([label{i},'-tailed'])
        if i == 1
            legend([type{t},'''s ',symbol{t},' (param.)'],...
                [type{t},'''s ',symbol{t},' (perm.)'],...
                '95% CI (param.)','','95% CI (perm.)','Location','best')
        end
        subplot(3,2,i+i), hold on
        plot(xaxis,r1,xaxis,r3,'--','LineWidth',2)
        plot(xaxis,ci1,'k',xaxis,ci3,'--r')
        plot(xaxis(p1<=alpha),r1(p1<=alpha),'ok','LineWidth',2)
        plot(xaxis(p3<=alpha),r2(p3<=alpha),'xr','LineWidth',2)
        xlim([0,nvar+1]), ylim([-1,1]), box on, grid on
        if i == 1
            title('Max-corrected')
        elseif i == 3
            xlabel('variable')
        end

        % Plot p-values
        figure(f2)
        subplot(3,2,i+i-1), hold on
        plot(xaxis,p1,'k',xaxis,p2,'--r','LineWidth',2)
        xlim([0,nvar+1]), ylim([0,1]), box on, grid on
        if i == 1
            title('Uncorrected')
        elseif i == 3
            xlabel('variable')
        end
        ylabel([label{i},'-tailed'])
        if i == 1
            legend('{\itp}-value (param.)','{\itp}-value (perm.)',...
                'Location','best')
        end
        subplot(3,2,i+i), hold on
        plot(xaxis,p1,'k',xaxis,p3,'--r','LineWidth',2)
        xlim([0,nvar+1]), ylim([0,1]), box on, grid on
        if i == 1
            title('Max-corrected')
        elseif i == 3
            xlabel('variable')
        end

    end

    fprintf('Parametric (uncorrect): %.1f ms\n',mean(toc1)*1e3)
    fprintf('Permutation (uncorrect): %.1f ms\n',mean(toc2)*1e3)
    fprintf('Permutation (max-corr.): %.1f ms\n',mean(toc3)*1e3)

end