function run_permucorr_examples
%RUN_PERMUCORR_EXAMPLES  Run permutation correlation test examples.
%   Generates random multivariate data for 2 "dependent" samples X and Y.
%   Each sample has 20 variables, each pair with a correlation of 0, except
%   for the first 5 variables which have a positive correlation, and the
%   second 5 variables which have a negative correlation. Each variable has
%   30 observations. Permutation tests based on the Pearson and Spearman
%   correlation coefficient are performed between the corresponding
%   variables of each sample for two-tailed, right-tailed and left-tailed
%   tests. The results are compared to those of the equivalent parametric
%   statistical tests (i.e. Student's t-distribution) using corr.m and
%   corrcoef.m.
%
%   Note: The parametric confidence intervals (CIs) generated by corrcoef.m
%   for the right-tailed and left-tailed tests are actually based on that
%   of a two-tailed test (as there is no option to specify the test tail in
%   corrcoef.m) and are thus slightly overestimated.
%
%   See also PERMUCORR CORR CORRCOEF.
%
%   PERMUTOOLS https://github.com/mickcrosse/PERMUTOOLS

%   References:
%       [1] Crosse MJ, Foxe JJ, Molholm S (2024) PERMUTOOLS: A MATLAB
%           Package for Multivariate Permutation Testing. arXiv 2401.09401.

%   © 2018-2024 Mick Crosse <crossemj@tcd.ie>
%   CNL, Albert Einstein College of Medicine, NY.
%   TCBE, Trinity College Dublin, Ireland.

% Generate random data
rng(42);
x = randn(30,20);
y = randn(30,20);
y(:,1:5) = y(:,1:5)+x(:,1:5)/2;
y(:,6:10) = y(:,6:10)-x(:,6:10);
xaxis = 1:20; alpha = 0.05;
tail = {'both','right','left'};
label = {'two','right','left'};
type = {'Pearson','Spearman'};
symbol = {'{\itr}','{\itρ}'};

for n = 1:numel(type)

    % Plot parametric & permutation CIs
    figure('Name',[type{n},'''s Correlation: coefficients & CIs'],...
        'NumberTitle','off')
    set(gcf,'color','w')
    for i = 1:numel(tail)
        [r1,p1] = corr(x,y,'tail',tail{i},'type',type{n});
        r1 = diag(r1); p1 = diag(p1);
        ci1 = zeros(2,20);
        for j = 1:20
            switch type{n}
                case 'Pearson'
                    [~,~,clwr,cupr] = corrcoef(x(:,j),y(:,j));
                case 'Spearman'
                    [~,~,clwr,cupr] = corrcoef(tiedrank(x(:,j)),...
                        tiedrank(y(:,j)));
            end
            switch tail{i}
                case 'right'
                    ci1(:,j) = [clwr(2);Inf];
                case 'left'
                    ci1(:,j) = [-Inf;cupr(2)];
                otherwise
                    ci1(:,j) = [clwr(2);cupr(2)];
            end
        end
        [r2,p2,ci2] = permucorr(x,y,'tail',tail{i},'type',type{n},...
            'correct',0);
        subplot(3,2,i+i-1), hold on
        plot(xaxis,r2,'LineWidth',3)
        plot(xaxis,ci1,'k',xaxis,ci2,'--r')
        plot(xaxis(p1<=alpha),r1(p1<=alpha),'ok','LineWidth',2)
        plot(xaxis(p2<=alpha),r2(p2<=alpha),'xr','LineWidth',2)
        xlim([0,21]), ylim([-2,2]), box on, grid on
        if i == 1
            title('Uncorrected')
        elseif i == 3
            xlabel('variable')
        end
        ylabel([label{i},'-tailed'])
        if i == 2
            legend([type{n},'''s ',symbol{n}],'95% CI (param.)','',...
                '95% CI (perm.)')
        end
        [r2,p2,ci2] = permucorr(x,y,'tail',tail{i},'type',type{n},...
            'correct',1);
        subplot(3,2,i+i), hold on
        plot(xaxis,r2,'LineWidth',3)
        plot(xaxis,ci1,'k',xaxis,ci2,'--r')
        plot(xaxis(p1<=alpha),r1(p1<=alpha),'ok','LineWidth',2)
        plot(xaxis(p2<=alpha),r2(p2<=alpha),'xr','LineWidth',2)
        xlim([0,21]), ylim([-2,2]), box on, grid on
        if i == 1
            title('Max-corrected')
        elseif i == 3
            xlabel('variable')
        end
    end

    % Plot parametric & permutation p-values
    figure('Name',[type{n},'''s Correlation: p-values'],...
        'NumberTitle','off')
    set(gcf,'color','w')
    for i = 1:numel(tail)
        [~,p1] = corr(x,y,'tail',tail{i},'type',type{n});
        p1 = diag(p1);
        [~,p2] = permucorr(x,y,'tail',tail{i},'type',type{n},'correct',0);
        subplot(3,2,i+i-1), hold on
        plot(xaxis,p1,'k',xaxis,p2,'--r','LineWidth',2)
        xlim([0,21]), ylim([0,1]), box on, grid on
        if i == 1
            title('Uncorrected')
        elseif i == 3
            xlabel('variable')
        end
        ylabel([label{i},'-tailed'])
        if i == 2
            legend('{\itp}-value (param.)','{\itp}-value (perm.)')
        end
        [~,p2] = permucorr(x,y,'tail',tail{i},'type',type{n},'correct',1);
        subplot(3,2,i+i), hold on
        plot(xaxis,p1,'k',xaxis,p2,'--r','LineWidth',2)
        xlim([0,21]), ylim([0,1]), box on, grid on
        if i == 1
            title('Max-corrected')
        elseif i == 3
            xlabel('variable')
        end
    end

end