function run_permumanova2_examples
%RUN_PERMUMANOVA2_EXAMPLES  Run permutation-based two-way MANOVA examples.
%   Generates random multivariate data for a 2x2 design along the rows of
%   X. X contains 20 sets of dependent variables (2 dimensions per set).
%   The groups have identical multivariate means of 0 for most variables,
%   except for the first 5 variables where Factor A induces a shift. Each
%   cell in the 2x2 design has 10 observations (40 total).
%
%   Permutation-based two-way MANOVAs are performed on the datasets using
%   standard and rank-transformed methods. Because MATLAB does not have a
%   native manova2 function, the results are compared to a parametric
%   baseline generated by applying Bartlett's Chi-square approximation
%   directly to the exact Wilks' Lambda statistics.
%
%   See also PERMUMANOVA2 PERMUMANOVA1.
%
%   PERMUTOOLS https://github.com/mickcrosse/PERMUTOOLS

%   References:
%       [1] Crosse MJ,Foxe JJ,Molholm S (2024) PERMUTOOLS: A MATLAB
%           Package for Multivariate Permutation Testing. arXiv 2401.09401.

%   © 2018-2026 Mick Crosse <crossemj@tcd.ie>
%   CNL,Albert Einstein College of Medicine,NY.
%   TCBE,Trinity College Dublin,Ireland.

% Set up experiment
nobs = 40; nvar = 20; ndep = 2;
xaxis = 1:nvar; alpha = 0.05;
group1 = [ones(20,1);2*ones(20,1)];
group2 = repmat([ones(10,1);2*ones(10,1)],2,1);
group = [group1,group2];
type = {'manova2','rank'};

% Generate random 3D data
rng(42);
x = randn(nobs,ndep,nvar);
x(group(:,1)==1,1,1:5) = x(group(:,1)==1,1,1:5) + 1.5;
x(group(:,1)==1,2,1:5) = x(group(:,1)==1,2,1:5) + 0.5;

for t = 1:numel(type)

    % Set up figure
    figure('Name',['Two-way (',type{t},') - Factor A'],'NumberTitle','off')
    set(gcf,'color','w')

    % Run parametric MANOVA equivalent
    tic
    switch type{t}
        case 'manova2'
            xparam = x;
        case 'rank'
            xparam = reshape(tiedrank(reshape(x,nobs,[])),nobs,ndep,nvar);
    end
    lambdaparam = permumanova2(xparam,group);
    lambda1 = lambdaparam(1,:);
    dfA = 1;
    dfE = nobs-4;
    dfchi2 = ndep*dfA;
    bartlettC = dfE+dfA-(ndep+dfA+1)/2;
    chi2stat = -bartlettC.*log(lambda1);
    p1 = 1-chi2cdf(chi2stat,dfchi2);
    chi2crit = chi2inv(1-alpha,dfchi2);
    crit = exp(-chi2crit/bartlettC);
    ci1 = [zeros(1,nvar);lambda1./crit];
    fprintf('Elapsed time (Param.): %.3f s\n',toc)

    % Run Permutation MANOVA (Uncorrected)
    tic
    [lambda2,p2,ci2] = permumanova2(x,group,'type',type{t},'correct',0);
    fprintf('Elapsed time (Perm. uncorr.): %.3f s\n',toc)

    % Isolate Factor A for plotting
    lambda2a = lambda2(1,:);
    p2a = p2(1,:);
    ci2a = squeeze(ci2(:,1,:));

    % Plot uncorrected test statistic & CIs
    subplot(2,2,1),hold on
    plot(xaxis,lambda1,'LineWidth',2)
    plot(xaxis,lambda2a,'--','LineWidth',2)
    plot(xaxis,ci1,'k',xaxis,ci2a,'--r')
    plot(xaxis(p1<=alpha),lambda1(p1<=alpha),'ok','LineWidth',2)
    plot(xaxis(p2a<=alpha),lambda2a(p2a<=alpha),'xr','LineWidth',2)
    xlim([0,nvar+1]), ylim([0,2]), box on, grid on
    title('Uncorrected'),ylabel('Wilks'' \Lambda')
    legend('Wilks'' \Lambda (param.)','Wilks'' \Lambda (perm.)',...
        '95% CI (param.)','95% CI (perm.)','Location','best')

    % Plot uncorrected p-values
    subplot(2,2,3),hold on
    plot(xaxis,p1,'k',xaxis,p2a,'--r','LineWidth',2)
    xlim([0,nvar+1]), ylim([0,1]), box on, grid on
    xlabel('variable'), ylabel('probability')
    legend('{\itp}-value (param.)','{\itp}-value (perm.)','Location','best')

    % Run permutation MANOVA (max-corrected)
    tic
    [lambda2,p2,ci2] = permumanova2(x,group,'type',type{t},'correct',1);
    fprintf('Elapsed time (Perm. max-corr.): %.3f s\n',toc)

    % Isolate Factor A for plotting
    lambda2a = lambda2(1,:);
    p2a = p2(1,:);
    ci2a = squeeze(ci2(:,1,:));

    % Plot max-corrected test statistic & CIs
    subplot(2,2,2),hold on
    plot(xaxis,lambda1,'LineWidth',2)
    plot(xaxis,lambda2a,'--','LineWidth',2)
    plot(xaxis,ci1,'k',xaxis,ci2a,'--r')
    plot(xaxis(p1<=alpha),lambda1(p1<=alpha),'ok','LineWidth',2)
    plot(xaxis(p2a<=alpha),lambda2a(p2a<=alpha),'xr','LineWidth',2)
    xlim([0,nvar+1]), ylim([0,2]), box on, grid on
    title('Max-corrected')

    % Plot max-corrected p-values
    subplot(2,2,4),hold on
    plot(xaxis,p1,'k',xaxis,p2a,'--r','LineWidth',2)
    xlim([0,nvar+1]), ylim([0,1]), box on, grid on
    xlabel('variable')

end